#!/bin/bash

case "$1" in
    start)
        /media/fat/Scripts/.octokeyz/octokeyz-mister &
        ;;

    stop)
        /media/fat/Scripts/.octokeyz/octokeyz-mister -stop
        ;;

    restart)
        /media/fat/Scripts/.octokeyz/octokeyz-mister -stop
        sleep 2
        /media/fat/Scripts/.octokeyz/octokeyz-mister &
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
