name: Main

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: main
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
            go-version-file: go.mod
            cache-dependency-path: go.sum

      - name: Build octokeyz-mister
        id: build
        run: |
          GOOS=linux GOARCH=arm go build -o root/Scripts/.octokeyz/octokeyz-mister
          cp -v Scripts/* root/Scripts/
          go build
          VERSION="$(./octokeyz-mister -v | sed s/^v//)"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          pushd root > /dev/null
          zip -r9 "../octokeyz-mister-${VERSION}.zip" *
          popd > /dev/null

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            octokeyz-mister-*.zip

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Get release metadata
        id: meta
        run: |
          version="$(echo "${{ github.ref }}" | sed 's,refs/tags/v,,')"
          echo "name=$(git tag -l --format="%(contents:subject)" "v${version}")" >> $GITHUB_OUTPUT
          git tag -l --format="%(contents:body)" "v${version}" > body.md

      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          name: ${{ steps.meta.outputs.name }}
          artifacts: dist/octokeyz-mister-*
          bodyFile: body.md
          generateReleaseNotes: true
